annotations:
  fips: 'true'
  images: '[]

    '
  licenses: Apache-2.0
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/common:2.41.0
  inglp.bitnami-secure-mirror/source-digest: sha256:6c0f000b49f8f2c99c18e7270ffdc28a70ebc812177d137701b3eab8cda4352c
  inglp.bitnami-secure-mirror/upstream-version: 2.41.0
apiVersion: v2
appVersion: 2.41.0
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/downloads/logos/bitnami-mark.png
keywords:
- common
- helper
- template
- function
- bitnami
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: common
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/common
type: library
version: 2.41.0-inglp.r0
