global:
  imageRegistry: ''
  imagePullSecrets: []
  security:
    allowInsecureImages: true
  compatibility:
    openshift:
      adaptSecurityContext: auto
  defaultFips: restricted
  clusterDomain: cluster.local
nameOverride: ''
fullnameOverride: ''
namespaceOverride: ''
kubeVersion: ''
clusterDomain: cluster.local
extraDeploy: []
commonLabels: {}
commonAnnotations: {}
diagnosticMode:
  enabled: false
  command:
  - sleep
  args:
  - infinity
image:
  registry: docker.io
  repository: inglp/bitnami-secure-nginx
  tag: 1.31.3-photon-5-r0
  digest: sha256:92069d635fd13eb4af4f831b88bb99a0757e2030bd996056670c0d3bd48a5d4f
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
enableDefaultInitContainers: true
automountServiceAccountToken: false
hostAliases: []
command: []
args: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
replicaCount: 1
revisionHistoryLimit: 10
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
podLabels: {}
podAnnotations: {}
podAffinityPreset: ''
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ''
  key: ''
  values: []
affinity: {}
hostNetwork: false
hostIPC: false
dnsPolicy: ''
dnsConfig: {}
nodeSelector: {}
tolerations: []
priorityClassName: ''
schedulerName: ''
runtimeClassName: ''
terminationGracePeriodSeconds: ''
topologySpreadConstraints: []
tls:
  enabled: true
  autoGenerated: true
  existingSecret: ''
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
  cert: ''
  key: ''
  ca: ''
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001
  sysctls: []
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault
containerPorts:
  http: 8080
  https: 8443
extraContainerPorts: []
resourcesPreset: nano
resources: {}
fips:
  openssl: ''
lifecycleHooks: {}
startupProbe:
  enabled: false
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 6
  successThreshold: 1
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
autoscaling:
  enabled: false
  minReplicas: ''
  maxReplicas: ''
  targetCPU: ''
  targetMemory: ''
extraVolumes: []
extraVolumeMounts: []
serviceAccount:
  create: true
  name: ''
  annotations: {}
  automountServiceAccountToken: false
sidecars: []
sidecarSingleProcessNamespace: false
initContainers: []
pdb:
  create: true
  minAvailable: ''
  maxUnavailable: ''
cloneStaticSiteFromGit:
  enabled: false
  image:
    registry: docker.io
    repository: inglp/bitnami-secure-git
    tag: 2.55.0-photon-5-r3
    digest: sha256:c02bdac0976e9edc06f5f4b262686b7c93192431d6eeffb7484ec664467a0c2f
    pullPolicy: IfNotPresent
    pullSecrets: []
  repository: ''
  branch: ''
  interval: 60
  fips:
    openssl: ''
  gitClone:
    command: []
    args: []
  gitSync:
    command: []
    args: []
    resourcesPreset: nano
    resources: {}
  extraEnvVars: []
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
serverBlock: ''
streamServerBlock: ''
existingServerBlockConfigmap: ''
existingStreamServerBlockConfigmap: ''
contextIncludes:
  main: ''
  events: ''
  http: ''
existingContextMainConfigmaps: []
existingContextEventsConfigmaps: []
existingContextHttpConfigmaps: []
staticSiteConfigmap: ''
staticSitePVC: ''
service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
  nodePorts:
    http: ''
    https: ''
  targetPort:
    http: http
    https: https
  clusterIP: ''
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  loadBalancerClass: ''
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  annotations: {}
  externalTrafficPolicy: Cluster
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
httpRoute:
  enabled: false
  annotations: {}
  labels: {}
  parentRefs: []
  hostnames:
  - nginx.local
  matches:
  - path:
      type: PathPrefix
      value: /
  filters: []
  extraRules: []
backendTLSPolicy:
  enabled: false
  annotations: {}
  labels: {}
  hostname: ''
  subjectAltNames: []
ingress:
  enabled: false
  selfSigned: false
  pathType: ImplementationSpecific
  apiVersion: ''
  hostname: nginx.local
  path: /
  annotations: {}
  ingressClassName: ''
  tls: false
  tlsWwwPrefix: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
healthIngress:
  enabled: false
  selfSigned: false
  pathType: ImplementationSpecific
  hostname: example.local
  path: /
  annotations: {}
  tls: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  ingressClassName: ''
  extraRules: []
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: inglp/bitnami-secure-nginx-exporter
    tag: 1.5.1-photon-5-r42
    digest: sha256:069f2ca55b715da8cc8788005f822f08dd275e1a60458139ff5c624eb390e7fa
    pullPolicy: IfNotPresent
    pullSecrets: []
  port: ''
  extraArgs: []
  containerPorts:
    metrics: 9113
  podAnnotations: {}
  securityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  service:
    port: 9113
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
  resourcesPreset: nano
  resources: {}
  fips:
    openssl: ''
    golang: restricted
  serviceMonitor:
    enabled: false
    namespace: ''
    tlsConfig: {}
    jobLabel: ''
    interval: ''
    scrapeTimeout: ''
    selector: {}
    labels: {}
    relabelings: []
    metricRelabelings: []
    honorLabels: false
  prometheusRule:
    enabled: false
    namespace: ''
    additionalLabels: {}
    rules: []
  customLivenessProbe: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 2
    successThreshold: 1
  customReadinessProbe: {}
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 2
    successThreshold: 1
  customStartupProbe: {}
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 10
    successThreshold: 1
