annotations:
  fips: 'true'
  images: "- name: mariadb\n  version: 12.2.2\n  image: registry-1.docker.io/bitnamisecure/mariadb:latest\n\
    - name: mysqld-exporter\n  version: 0.19.0\n  image: registry-1.docker.io/bitnamisecure/mysqld-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n"
  licenses: Apache-2.0
  tanzuCategory: service
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/mariadb:25.1.2
  inglp.bitnami-secure-mirror/source-digest: sha256:4eea9a43927f6026ffa79e26679348b2c31ca2940185048b5682d6b1e8d4852e
  inglp.bitnami-secure-mirror/upstream-version: 25.1.2
apiVersion: v2
appVersion: 12.2.2
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.39.0-inglp.r0
description: MariaDB is an open source, community-developed SQL database server that
  is widely in use around the world due to its enterprise features, flexibility, and
  collaboration with leading tech firms.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mariadb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
version: 25.1.2-inglp.r0
