global:
  imageRegistry: ''
  imagePullSecrets: []
  defaultStorageClass: ''
  security:
    allowInsecureImages: true
  compatibility:
    openshift:
      adaptSecurityContext: auto
  defaultFips: restricted
kubeVersion: ''
nameOverride: ''
fullnameOverride: ''
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
schedulerName: ''
runtimeClassName: ''
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
  - sleep
  args:
  - infinity
serviceBindings:
  enabled: false
image:
  registry: docker.io
  repository: inglp/bitnami-secure-mariadb
  tag: 12.3.2-photon-5-r2
  digest: sha256:54fc0274284a4bd700779d0ef73dfc99f8e82934612124d28b69e4469d4ce321
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
architecture: standalone
auth:
  rootPassword: ''
  database: my_database
  username: ''
  password: ''
  replicationUser: replicator
  replicationPassword: ''
  existingSecret: ''
  forcePassword: false
  usePasswordFiles: true
  customPasswordFiles: {}
initdbScripts: {}
initdbScriptsConfigMap: ''
tls:
  enabled: false
  existingSecret: ''
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ''
  ca: ''
  cert: ''
  key: ''
  autoGenerated:
    enabled: true
    engine: helm
    extraSANs: []
    loopback: false
    certManager:
      existingIssuer: ''
      existingIssuerKind: ''
      keySize: 2048
      keyAlgorithm: RSA
      duration: 2160h
      renewBefore: 360h
tde:
  enabled: false
  existingSecret: ''
  randomKeyFilename: keyfile.key
  encryptedKeyFilename: keyfile.enc
  fileKeyManagementEncryptionAlgorithm: AES_CTR
  innodbEncryptTables: FORCE
  innodbEncryptLog: 'ON'
  innodbEncryptTemporaryTables: 'ON'
  encryptTmpDiskTables: 'ON'
  encryptTmpTiles: 'ON'
  encryptBINLOG: 'ON'
  ariaEncryptTables: 'ON'
  innodbEncryptionThreads: 4
  secretsStoreProvider:
    enabled: false
    provider: vault
    vault:
      roleName: ''
      address: ''
      authMountPath: ''
      randomKeySecretPath: ''
      randomKeySecretKey: ''
      encryptedKeySecretPath: ''
      encryptedKeySecretKey: ''
primary:
  name: primary
  command: []
  args: []
  lifecycleHooks: {}
  automountServiceAccountToken: false
  hostAliases: []
  containerPorts:
    mysql: 3306
  configuration: '[mysqld]

    skip-name-resolve

    explicit_defaults_for_timestamp

    basedir=/opt/bitnami/mariadb

    datadir=/bitnami/mariadb/data

    plugin_dir=/opt/bitnami/mariadb/plugin

    port={{ .Values.primary.containerPorts.mysql }}

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    tmpdir=/opt/bitnami/mariadb/tmp

    max_allowed_packet=16M

    bind-address=*

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

    log-error=/opt/bitnami/mariadb/logs/mysqld.log

    character-set-server=UTF8

    collation-server=utf8_general_ci

    slow_query_log=0

    long_query_time=10.0

    binlog_expire_logs_seconds=2592000

    {{- if .Values.tls.enabled }}

    ssl_cert=/opt/bitnami/mariadb/certs/tls.crt

    ssl_key=/opt/bitnami/mariadb/certs/tls.key

    {{- if or .Values.tls.autoGenerated.enabled .Values.tls.ca .Values.tls.existingSecret
    }}

    ssl_ca=/opt/bitnami/mariadb/certs/ca.crt

    {{- end }}

    {{- end }}

    {{- if .Values.tde.enabled }}

    plugin_load_add=file_key_management

    file_key_management_filename=/opt/bitnami/mariadb/tde/{{ .Values.tde.encryptedKeyFilename
    }}

    file_key_management_filekey=FILE:/opt/bitnami/mariadb/tde/{{ .Values.tde.randomKeyFilename
    }}

    file_key_management_encryption_algorithm={{ .Values.tde.fileKeyManagementEncryptionAlgorithm
    }}

    innodb_encrypt_tables={{ .Values.tde.innodbEncryptTables }}

    innodb_encrypt_log={{ .Values.tde.innodbEncryptLog }}

    innodb_encrypt_temporary_tables={{ .Values.tde.innodbEncryptTemporaryTables }}

    innodb_encryption_threads={{ .Values.tde.innodbEncryptionThreads }}

    encrypt_tmp_disk_tables={{ .Values.tde.encryptTmpDiskTables }}

    encrypt_tmp_files={{ .Values.tde.encryptTmpTiles }}

    encrypt_binlog={{ .Values.tde.encryptBINLOG }}

    aria_encrypt_tables={{ .Values.tde.ariaEncryptTables }}

    {{- end }}


    [client]

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    default-character-set=UTF8

    plugin_dir=/opt/bitnami/mariadb/plugin


    [manager]

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid'
  existingConfigmap: ''
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podLabels: {}
  podAffinityPreset: ''
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ''
    key: ''
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  schedulerName: ''
  terminationGracePeriodSeconds: ''
  podManagementPolicy: ''
  topologySpreadConstraints: []
  priorityClassName: ''
  runtimeClassName: ''
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  resourcesPreset: small
  resources: {}
  fips:
    openssl: ''
  startupProbe:
    enabled: false
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  startupWaitOptions: {}
  extraFlags: ''
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  persistence:
    enabled: true
    existingClaim: ''
    subPath: ''
    storageClass: ''
    labels: {}
    annotations: {}
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    selector: {}
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      metrics: 9104
    nodePorts:
      mysql: ''
    clusterIP: ''
    loadBalancerIP: ''
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
  pdb:
    create: true
    minAvailable: ''
    maxUnavailable: ''
  revisionHistoryLimit: 10
secondary:
  name: secondary
  replicaCount: 1
  command: []
  args: []
  lifecycleHooks: {}
  automountServiceAccountToken: false
  hostAliases: []
  containerPorts:
    mysql: 3306
  configuration: '[mysqld]

    skip-name-resolve

    explicit_defaults_for_timestamp

    basedir=/opt/bitnami/mariadb

    datadir=/bitnami/mariadb/data

    port={{ .Values.secondary.containerPorts.mysql }}

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    tmpdir=/opt/bitnami/mariadb/tmp

    max_allowed_packet=16M

    bind-address=0.0.0.0

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

    log-error=/opt/bitnami/mariadb/logs/mysqld.log

    character-set-server=UTF8

    collation-server=utf8_general_ci

    slow_query_log=0

    long_query_time=10.0

    binlog_expire_logs_seconds=2592000

    {{- if .Values.tls.enabled }}

    ssl_cert=/opt/bitnami/mariadb/certs/tls.crt

    ssl_key=/opt/bitnami/mariadb/certs/tls.key

    {{- if or .Values.tls.autoGenerated.enabled .Values.tls.ca .Values.tls.existingSecret
    }}

    ssl_ca=/opt/bitnami/mariadb/certs/ca.crt

    {{- end }}

    {{- end }}


    [client]

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    default-character-set=UTF8


    [manager]

    port=3306

    socket=/opt/bitnami/mariadb/tmp/mysql.sock

    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid'
  existingConfigmap: ''
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podLabels: {}
  podAffinityPreset: ''
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ''
    key: ''
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ''
  runtimeClassName: ''
  schedulerName: ''
  terminationGracePeriodSeconds: ''
  podManagementPolicy: ''
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  resourcesPreset: small
  resources: {}
  startupProbe:
    enabled: false
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 10
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  customStartupProbe: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  startupWaitOptions: {}
  extraFlags: ''
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  persistence:
    enabled: true
    subPath: ''
    storageClass: ''
    labels: {}
    annotations: {}
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    selector: {}
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      metrics: 9104
    nodePorts:
      mysql: ''
    clusterIP: ''
    loadBalancerIP: ''
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
  pdb:
    create: true
    minAvailable: ''
    maxUnavailable: ''
  revisionHistoryLimit: 10
  fips:
    openssl: ''
serviceAccount:
  create: true
  name: ''
  annotations: {}
  automountServiceAccountToken: false
rbac:
  create: false
passwordUpdateJob:
  enabled: false
  backoffLimit: 10
  command: []
  args: []
  extraCommands: ''
  previousPasswords:
    rootPassword: ''
    password: ''
    replicationPassword: ''
    existingSecret: ''
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  resourcesPreset: micro
  resources: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  automountServiceAccountToken: false
  hostAliases: []
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  fips:
    openssl: ''
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: inglp/bitnami-secure-os-shell
    tag: 5-photon-5-r87
    digest: sha256:6b315d78dc23577e0106c71203f4df4da2cc8b1ffe8b65ac9d76bb78620c4890
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: nano
  resources: {}
  fips:
    openssl: ''
metrics:
  enabled: false
  auth:
    username: exporter
    password: ''
    existingSecret: ''
  image:
    registry: docker.io
    repository: inglp/bitnami-secure-mysqld-exporter
    tag: 0.19.0-photon-5-r17
    digest: sha256:62ebcb49d9b229b05bd0ff0394e984820aaa7dba129a81d40f848ea2354386b1
    pullPolicy: IfNotPresent
    pullSecrets: []
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9104'
  extraArgs:
    primary: []
    secondary: []
  extraVolumeMounts:
    primary: []
    secondary: []
  containerPorts:
    http: 9104
  containerSecurityContext:
    enabled: true
    privileged: false
    runAsNonRoot: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
  resourcesPreset: nano
  resources: {}
  fips:
    openssl: ''
    golang: relaxed
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  serviceMonitor:
    enabled: false
    namespace: ''
    jobLabel: ''
    interval: 30s
    scrapeTimeout: ''
    relabelings: []
    metricRelabelings: []
    honorLabels: false
    selector: {}
    labels: {}
  prometheusRule:
    enabled: false
    namespace: ''
    additionalLabels: {}
    rules: []
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
