annotations:
  fips: 'true'
  images: "- name: memcached\n  version: 1.6.45\n  image: registry-1.docker.io/bitnamisecure/memcached:latest\n\
    - name: memcached-exporter\n  version: 0.16.0\n  image: registry-1.docker.io/bitnamisecure/memcached-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n"
  licenses: Apache-2.0
  tanzuCategory: service
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/memcached:8.7.0
  inglp.bitnami-secure-mirror/source-digest: sha256:007adc7951f508fdf15be444946174790c053813ab04ea1b63ed41a6ef9873f3
  inglp.bitnami-secure-mirror/upstream-version: 8.7.0
apiVersion: v2
appVersion: 1.6.45
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.41.0-inglp.r0
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
  by alleviating database load.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: memcached
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/memcached
version: 8.7.0-inglp.r0
