annotations:
  fips: 'true'
  images: "- name: memcached\n  version: 1.6.41\n  image: registry-1.docker.io/bitnamisecure/memcached:latest\n\
    - name: memcached-exporter\n  version: 0.16.0\n  image: registry-1.docker.io/bitnamisecure/memcached-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n"
  licenses: Apache-2.0
  tanzuCategory: service
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/memcached:8.5.2
  inglp.bitnami-secure-mirror/source-digest: sha256:6fe91bc3568905bfad1562d28526ddf8fc7d9d24b2cfb7397a49c710fb3c6649
  inglp.bitnami-secure-mirror/upstream-version: 8.5.2
apiVersion: v2
appVersion: 1.6.41
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.39.0-inglp.r0
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
  by alleviating database load.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: memcached
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/memcached
version: 8.5.2-inglp.r0
