annotations:
  fips: 'true'
  images: "- name: apache-exporter\n  version: 1.0.12\n  image: registry-1.docker.io/bitnamisecure/apache-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n\
    - name: wordpress\n  version: 6.9.4\n  image: registry-1.docker.io/bitnamisecure/wordpress:latest\n"
  licenses: Apache-2.0
  tanzuCategory: application
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/wordpress:30.1.1
  inglp.bitnami-secure-mirror/source-digest: sha256:01dad444ca63f05f0043d97fc9270c42e7e3990cc28d54dc9b3ff598b79faf19
  inglp.bitnami-secure-mirror/upstream-version: 30.1.1
apiVersion: v2
appVersion: 6.9.4
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 8.5.1-inglp.r0
- condition: mariadb.enabled
  name: mariadb
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 25.1.1-inglp.r0
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.39.0-inglp.r0
description: WordPress is the world's most popular blogging and content management
  platform. Powerful yet simple, everyone from students to global corporations use
  it to build beautiful, functional websites.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- application
- blog
- cms
- http
- php
- web
- wordpress
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: wordpress
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/wordpress
version: 30.1.1-inglp.r0
