annotations:
  fips: 'true'
  images: "- name: apache-exporter\n  version: 1.1.1\n  image: registry-1.docker.io/bitnamisecure/apache-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n\
    - name: wordpress\n  version: 7.0.2\n  image: registry-1.docker.io/bitnamisecure/wordpress:latest\n"
  licenses: Apache-2.0
  tanzuCategory: application
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/wordpress:32.1.13
  inglp.bitnami-secure-mirror/source-digest: sha256:bb9fb29dc263852ffb2f7335db6b94b3dadc23d96fd61a996b1146a182962627
  inglp.bitnami-secure-mirror/upstream-version: 32.1.13
apiVersion: v2
appVersion: 7.0.2
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 8.7.0-inglp.r0
- condition: mariadb.enabled
  name: mariadb
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 26.2.0-inglp.r0
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.41.0-inglp.r0
description: WordPress is the world's most popular blogging and content management
  platform. Powerful yet simple, everyone from students to global corporations use
  it to build beautiful, functional websites.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- application
- blog
- cms
- http
- php
- web
- wordpress
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: wordpress
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/wordpress
version: 32.1.13-inglp.r0
