annotations:
  fips: 'true'
  images: "- name: apache-exporter\n  version: 1.1.1\n  image: registry-1.docker.io/bitnamisecure/apache-exporter:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n\
    - name: wordpress\n  version: 7.1.0\n  image: registry-1.docker.io/bitnamisecure/wordpress:latest\n"
  licenses: Apache-2.0
  tanzuCategory: application
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/wordpress:33.0.10
  inglp.bitnami-secure-mirror/source-digest: sha256:bc4d1a3c94dc531175393e215b286dfb8c2a71bed65e6157c21a1729cca0c0b7
  inglp.bitnami-secure-mirror/upstream-version: 33.0.10
apiVersion: v2
appVersion: 7.1.0
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 8.7.9-inglp.r1
- condition: mariadb.enabled
  name: mariadb
  repository: https://inglp.github.io/bitnami-secure-charts
  version: 27.0.7-inglp.r1
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.41.0-inglp.r0
description: WordPress is the world's most popular blogging and content management
  platform. Powerful yet simple, everyone from students to global corporations use
  it to build beautiful, functional websites.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- application
- blog
- cms
- http
- php
- web
- wordpress
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: wordpress
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/wordpress
version: 33.0.10-inglp.r0
