annotations:
  fips: 'true'
  images: "- name: kube-rbac-proxy\n  version: 0.22.0\n  image: registry-1.docker.io/bitnamisecure/kube-rbac-proxy:latest\n\
    - name: kubectl\n  version: 1.36.2\n  image: registry-1.docker.io/bitnamisecure/kubectl:latest\n\
    - name: mcp-mongodb\n  version: 1.12.0\n  image: registry-1.docker.io/bitnamisecure/mcp-mongodb:latest\n\
    - name: mongodb\n  version: 8.3.4\n  image: registry-1.docker.io/bitnamisecure/mongodb:latest\n\
    - name: mongodb-exporter\n  version: 0.51.0\n  image: registry-1.docker.io/bitnamisecure/mongodb-exporter:latest\n\
    - name: nginx\n  version: 1.31.1\n  image: registry-1.docker.io/bitnamisecure/nginx:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n"
  licenses: Apache-2.0
  tanzuCategory: service
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/mongodb:19.1.11
  inglp.bitnami-secure-mirror/source-digest: sha256:1d003439a07f4851299742f9ad891a86110193d5b644e2ed6d13cd513cd36ddf
  inglp.bitnami-secure-mirror/upstream-version: 19.1.11
apiVersion: v2
appVersion: 8.3.4
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.40.0-inglp.r0
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it
  stores data in JSON-like documents. Automated scalability and high-performance.
  Ideal for developing cloud native applications.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mongodb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mongodb
version: 19.1.11-inglp.r2
