annotations:
  fips: 'true'
  images: "- name: kubectl\n  version: 1.36.1\n  image: registry-1.docker.io/bitnamisecure/kubectl:latest\n\
    - name: os-shell\n  version: \"5\"\n  image: registry-1.docker.io/bitnamisecure/os-shell:latest\n\
    - name: redis\n  version: 8.8.0\n  image: registry-1.docker.io/bitnamisecure/redis:latest\n\
    - name: redis-exporter\n  version: 1.86.0\n  image: registry-1.docker.io/bitnamisecure/redis-exporter:latest\n\
    - name: redis-sentinel\n  version: 8.8.0\n  image: registry-1.docker.io/bitnamisecure/redis-sentinel:latest\n"
  licenses: Apache-2.0
  tanzuCategory: service
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/redis:27.0.8
  inglp.bitnami-secure-mirror/source-digest: sha256:d646f6f334c73eb4d89e4d5bbd7741d412d79a55c92ed2d18852047881da364f
  inglp.bitnami-secure-mirror/upstream-version: 27.0.8
apiVersion: v2
appVersion: 8.8.0
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.40.0-inglp.r0
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 27.0.8-inglp.r0
