annotations:
  fips: 'true'
  images: "- name: haproxy\n  version: 3.2.19\n  image: registry-1.docker.io/bitnamisecure/haproxy:latest\n"
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
  inglp.bitnami-secure-mirror/source-chart: registry-1.docker.io/bitnamichartssecure/haproxy:3.5.4
  inglp.bitnami-secure-mirror/source-digest: sha256:d596c45ce88739c70c623930f1b2f1869495f7a16e1f29f3bbdb3142b72c55c0
  inglp.bitnami-secure-mirror/upstream-version: 3.5.4
apiVersion: v2
appVersion: 3.2.19
dependencies:
- name: common
  repository: https://inglp.github.io/bitnami-secure-charts
  tags:
  - bitnami-common
  version: 2.40.0-inglp.r0
description: HAProxy is a TCP proxy and a HTTP reverse proxy. It supports SSL termination
  and offloading, TCP and HTTP normalization, traffic regulation, caching and protection
  against DDoS attacks.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/haproxy/img/haproxy-stack-220x234.png
keywords:
- haproxy
- proxy
- infrastructure
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: haproxy
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/haproxy
version: 3.5.4-inglp.r0
